### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
This looks right indeed, but, regarding the commit message: "minor typo" does not sound like the fix can have a functional effect, but here two macros are changed and it can impact the `param.a0` value passed to the TEE, right? So I would recommend changing the commit message.

**Comment by vchong** [comment]
@jforissier Something like 'Fix teesmc macro definitions'?

**Comment by jforissier** [comment]
@vchong sorry for nitpicking... Yes, much better with the word 'fix'. Even beter IMO: 'Fix TEESMC{32,64}_FASTCALL_RETURN_FROM_RPC'.

**Comment by vchong** [comment]
@jforissier Np :). That's what reviews are for.
@pascal-brand-st-dev Commit message updated and tags applied.
Thanks all!

**Pull request merged**
